## Desafio: Caixeiro-viajante

In [1]:
from itertools import combinations, permutations
import numpy as np

In [35]:
N = int(input("Insira o numero de cidades a serem visitadas"))
cidades = range(1, N+1)

# Gerando uma lista com os trechos possíveis, sem repetição
arestas = tuple(combinations(cidades, 2))
# print(arestas)
adj = np.zeros((N,N), dtype=int)

for aresta in arestas:
    linha = aresta[0]
    coluna = aresta[1]
    peso = int(input(f'Insira a distância entre {linha} e {coluna}'))
    # peso = random.randint(1,10)
    adj[linha-1][coluna-1] = peso
    adj[coluna-1][linha-1] = peso

print(adj)

[[0 3 5]
 [3 0 7]
 [5 7 0]]


### Zona de Testes

In [36]:
# Transforma a matriz de adjacencia em uma matriz triangular para desconsiderar os pesos duplicados e. g. 1 -> 2 == 2 -> 1
adjTriangular = np.triu(adj)
# Criando um vetor de zeros para catalogar os vértices visitados
seVisita = np.zeros((N), dtype=bool)
print(adjTriangular)

[[0 3 5]
 [0 0 7]
 [0 0 0]]


In [33]:
# Encontra o menor peso na matriz de adjacência, desconsiderando os zeros
minPeso = np.min(adjTriangular[np.nonzero(adjTriangular)])
# Retorna os indexes onde o valor do elemento é igual ao mínimo (podendo ser mais de 1. e.g. min = 3, existem 2 elementos 3 na matriz)
minPesoIndex = np.nonzero(adjTriangular==minPeso)

print(minPesoIndex)
# Atualizando o catalogo de vértices visitados
seVisita[minPesoIndex[0][0]] = True
seVisita[minPesoIndex[1][0]] = True
borda1 = minPesoIndex[0][0]
borda2 = minPesoIndex[1][0]
# arvore = 

# Retorna o index das cidades visitadas
visitados = np.nonzero(seVisita)
# Retorna o index das cidades não visitadas
naoVisitados = np.where(seVisita == 0)

# Zerando o menor valor já adicionado para não ser computado outra vez
adjTriangular[borda1][borda2] = 0

# Descobrindo qual vértice da árvore está ligado a próxima aresta de menor grau
menorBorda = np.minimum(adjTriangular[borda1], adjTriangular[borda2])

print(borda1)
print(borda2)
print(menorBorda)
print(np.nonzero(adjTriangular==menorBorda))

(array([1], dtype=int64), array([2], dtype=int64))
1
2
[0 0 0]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [40]:
print(adjTriangular[borda2])


[0 0 0]


In [14]:
# Quantidade de soluções possíveis
n = int(input('Insira o numero de cidades: '))
if n == 1:
    print(1)
else:
    print(f'Existem {(2**(n-1))/2} soluções possíveis')

Existem 3.1691265005705735e+29 soluções possíveis


In [34]:
from time import time

# Nmax = 28
N = 25
# N = int(input('Insira o número de cidades: '))

start = time()
A = np.arange(1,N+1, dtype=np.int8)
B = A.copy()
for i in np.arange(1, A.size, dtype=np.int8):
    B = A.copy()
    B.T[[0,i]] = B.T[[i,0]]
    A = np.vstack((A, B))
end = time()
print(f'Tempo decorrido via NumPy: {end-start} s')

start2 = time()
lista = [i for i in range(1, N+1)]
casos = [lista]
for i in range(2, len(lista)+1):
    for j in range(len(casos)):
        x = casos[j].copy()
        x.remove(i)
        x.insert(0,i)
        casos.append(x)
end2 = time()
print(f'Tempo decorrido via looping: {end2-start2} s')

Tempo decorrido via NumPy: 0.4135279655456543s
Tempo decorrido via looping: 22.75102472305298s
