## Desafio: Caixeiro-viajante

In [3]:
from itertools import combinations, permutations
import numpy as np

In [65]:
N = int(input("Insira o numero de cidades a serem visitadas"))
cidades = range(1, N+1)

# Gerando uma lista com os trechos possíveis, sem repetição
arestas = tuple(combinations(cidades, 2))
# print(arestas)
adj = np.zeros((N,N), dtype=int)

for aresta in arestas:
    linha = aresta[0]
    coluna = aresta[1]
    peso = int(input(f'Insira a distância entre {linha} e {coluna}'))
    # peso = random.randint(1,10)
    adj[linha-1][coluna-1] = peso
    adj[coluna-1][linha-1] = peso

print(adj)

[[0 3 3]
 [3 0 5]
 [3 5 0]]


### Zona de Testes

In [ ]:
# import random
# tentando criar uma matriz de adjacencia
adj = np.zeros((N,N), dtype=int)

for edge in edges:
    linha = edge[0]
    coluna = edge[1]
    peso = int(input(f'Insira a distância entre {linha} e {coluna}'))
    # peso = random.randint(1,10)
    adj[linha-1][coluna-1] = peso
    adj[coluna-1][linha-1] = peso

print(adj)

In [76]:
# Transforma a matriz de adjacencia em uma matriz triangular para desconsiderar os pesos duplicados e. g. 1 -> 2 == 2 -> 1
adjTriangular = np.triu(adj)
# Criando um vetor de zeros para catalogar os vértices visitados
seVisita = np.zeros((N), dtype=bool)

[[0 3 3]
 [0 0 5]
 [0 0 0]]
[False False False]


In [77]:
# Encontra o menor peso na matriz de adjacência, desconsiderando os zeros
minPeso = np.min(adjTriangular[np.nonzero(adjTriangular)])
# Retorna os indexes onde o valor do elemento é igual ao mínimo (podendo ser mais de 1. e.g. min = 3, existem 2 elementos 3 na matriz)
minPesoIndex = np.nonzero(adjTriangular==minPeso)
# Atualizando o catalogo de vértices visitados
seVisita[minPesoIndex[0][0]] = True
seVisita[minPesoIndex[1][0]] = True

# Retorna o index das cidades visitadas
Visitados = np.nonzero(seVisita)
# Retorna o index das cidades não visitadas
naoVisitados = np.where(seVisita == 0)

minPeso = np.min(adjTriangular[np.nonzero(adjTriangular)])
minPesoIndex = np.nonzero(adjTriangular==3)

(array([0, 0], dtype=int64), array([1, 2], dtype=int64))


In [ ]:
while np.isin(0, seVisita):
    